language: node_js
node_js:
  - "8"

sudo: false

env:
  - NODE_ENV=production

branches:
  only:
    - master

before_install:
  - npm install -g surge

install:
  - npm install

script:
  - echo "Building..."
  - npm run build

after_success:
  - ls -l ./build
  - surge -p ./build --domain ideenegocios.com.ar
