language: node_js
node_js:
  - "8"

sudo: false

env:
  - NODE_ENV=production

branches:
  only:
    - master

install:
  - npm install

script:
  - echo "Building..."
  - ls -l .
  - npm run build

after_success:
  - ls -l ./build
  - npm run deploy
